# JOINS Assignment 5 BABI 4005

In [1]:
import pandas as pd
import os

## Inserting Student Survey Dataset

In [2]:
# Loading the cleaned student dataset
cleaned_data = pd.read_csv("C:/Users/Hp/Downloads/Cleaned_Student_Survey_PAWANCSV_20250212 (1).csv")

## Adding Fake Employment Data to Student Survey Dataset

### Why We Created Fake Data?
Since no real dataset was available to merge with our **Cleaned Student Survey Data**, I created a **fake dataset** using Chatgpt containing employment statistics based on the **Program** field.
This dataset helps analyze:
- **Employment rates (%)** for graduates of each program.
- **Industry placements** (e.g., BITMAN graduates go into Tech, Babi students into Analytics, HRMG into Human Resources ).
- **Average salary after graduation** for different programs.

In [3]:
# Loading the fake employment dataset
employment_data = pd.read_csv("C:/Users/Hp/Downloads/standardized_fake_employment_data.csv")

### **Type of Merge Used**
We used a **left join (`how="left"`)** because:
- It ensures **all students remain in the dataset**, even if their program doesn't have employment data.
- If employment data is missing for a program, the new columns (`Employment_Rate`, `Industry_Placement`, `Avg_Salary_After_Graduation`) will contain **NaN values**.
- This approach keeps the dataset intact while adding valuable employment insights.


### **Handling Missing Values (`NaN`)**
Some students may have **NaN values** in employment-related columns. This happens if:
- Their program was **not included** in the fake employment dataset.
- The dataset lacks **employment statistics** for that specific program.

We can handle missing values by:
- **Filling NaNs with "Unknown"** for categorical fields like `Industry_Placement`.
- **Replacing NaNs with median values** for numerical fields like `Avg_Salary_After_Graduation`.

In [8]:
# Merged using "Program" as the key
merged_data = pd.merge(cleaned_data, employment_data, on="Program", how="left")

In [9]:
# Define the path to Downloads
downloads_path = os.path.expanduser("~/Downloads/asgnmerged_student_employment_data.csv")

### **Final Dataset Saved to downlaods**

In [6]:
# Save the merged dataset to Downloads
merged_data.to_csv(downloads_path, index=False)

In [7]:
# Confirm the file location
print(f"File saved to: {downloads_path}")


# Display first few rows
merged_data.head()

File saved to: C:\Users\Hp/Downloads/asgnmerged_student_employment_data.csv

,Program,Gender,Age,Organization,Parents,Food_Lodging,Transport,Entertainment,CellCost,Sleep,...,Tuition,Coffee_Daily,Height (cm),Weight (kg),Prev_Monthly_Salary,Expected_Monthly_Salary,BMI,Employment_Rate (%),Industry_Placement,Avg_Salary_After_Graduation
0,Hrmg,Female,22.0,. Non-profit or Government Agency,No,700.0,0.0,100.0,68.0,8.0,...,No,0.0,177.80,110.0,1400.0,4000.0,34.795988,85,Human Resources,45000
1,Hrmg,Female,24.0,. Small Company,Yes,300.0,600.0,150.0,60.0,8.0,...,Yes,2.0,175.00,63.0,2000.0,3750.0,20.571429,85,Human Resources,45000
2,Hrmg,Male,24.0,. Small Company,Yes,200.0,100.0,150.0,82.0,6.0,...,No,0.0,182.88,100.0,2000.0,3500.0,29.899751,85,Human Resources,45000
3,Hrmg,Female,34.0,. Large Corporation,Yes,300.0,500.0,400.0,70.0,7.0,...,No,1.0,162.56,61.3,2500.0,3500.0,23.197068,85,Human Resources,45000
4,Hrmg,Female,24.0,. Small Company,Yes,500.0,300.0,100.0,90.0,7.0,...,Yes,1.0,160.00,54.0,0.0,3800.0,21.093750,85,Human Resources,45000